---
title: "A2.2"
author: "Alice Destrait"
date: "2024-02-21"
output:
  html_document:
    df_print: paged
---
```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)
library(sf)
library(zipcodeR)
library(tigris)
```

only new mexico data
```{r Overview df, message=FALSE, warning=FALSE}
pain_killer <- read_csv("data/arcos-nm-statewide-itemized.csv")
us_states <- read_sf("data/cb_2018_us_state_20m.shp")
df <- as.data.frame(pain_killer)
print(nrow(df))
head(df, 5)
```

still thinking if I should delete the ones with high nan
```{r missing data, message=FALSE, warning=FALSE}
colSums(is.na(df))
```

deleting columns with 1 unique value and change column names to lowercase
```{r cleaning df, message=FALSE, warning=FALSE}
names(df) <- tolower(names(df))
df <- df[, !(names(df) %in% c("transaction_code", "measure", "buyer_state"))]
```


```{r graph 1, message=FALSE, warning=FALSE}
df$transaction_date <- as.Date(df$transaction_date)

df$year <- format(df$transaction_date, "%Y")
df$month <- format(df$transaction_date, "%m")

# Aggregate the data by year and month
transaction_counts <- aggregate(df$transaction_date, 
                                by = list(year = df$year, month = df$month), 
                                FUN = length)
colnames(transaction_counts) <- c("year", "month", "Transaction_Count")

# Convert year and month to a Date object
transaction_counts$transaction_date <- as.Date(paste(transaction_counts$year, 
                                                      transaction_counts$month, 
                                                      "01", 
                                                      sep = "-"))

# Define a custom function to format the date labels
custom_date_labels <- function(x) {
  ifelse(format(x, "%m") == "01", format(x, "%Y"), "")
}

# Create the plot with custom date labels and breaks by 3 months
ggplot(transaction_counts, aes(x = transaction_date, y = Transaction_Count)) +
  geom_line(color = "#6c04a4") +
  scale_x_date(date_breaks = "3 months", labels = custom_date_labels, minor_breaks = NULL) +
  labs(title = "Transactions per Month",
       x = "Year",
       y = "Transactions") +
  theme_minimal()



```

```{r Misleading 1st graph}
recent_years <- subset(transaction_counts, as.numeric(year) >= 2006 & as.numeric(year) <= 2011)

# Create the plot with custom date labels and breaks by 3 months
plot <- ggplot(recent_years, aes(x = transaction_date, y = Transaction_Count)) +
  geom_line(color = "#6c04a4") +
  scale_x_date(date_breaks = "1 year", labels = scales::date_format("%Y")) +  # Adjust date breaks and format
  labs(title = "Monthly Transaction Trends", title.font = element_text(family = "Arial"), 
       subtitle = "Opioid Medication Transactions For The Last Six Years",
       subtitle.font = element_text(family = "Arial"),
       x = "Year",
       y = "Transactions") +
  theme_minimal() +
  theme(
    plot.title = element_text(
      face = "bold", 
      color = "black", 
      size = 16),
    plot.subtitle = element_text( 
      color = "darkgray", 
      size = 14, 
      hjust = 0, vjust = 1),
    axis.text.x = element_text(color = "darkgray"),  # Adjust x-axis label color
    axis.title.x = element_blank()  # Remove x-axis label
  )

print(plot)


```

```{r}
buyer_name_total_count <- df %>%
  group_by(buyer_name) %>%
  summarise(total_count = sum(n())) %>%
  arrange(desc(total_count)) %>%
  slice_head(n = 5)  # Select top 5 buyer_names with the highest total count

pill_data <- mutate(df, 
                    Era = case_when(
                      year >= 2006 & year <= 2009 ~ "Rise (2006-2009)",
                      year >= 2010 & year <= 2014 ~ "Peak (2010-2014)",
                      year >= 2015 & year <= 2019 ~ "Fall (2015-2019)"
                    ))

# Count occurrences of each distributor in each era
era_distribution <- pill_data %>%
  group_by(Era, buyer_name) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  group_by(Era) %>%
  top_n(5, Count)

era_distribution_summarized <- era_distribution %>%
  group_by(Era, buyer_name) %>%
  summarise(Count = sum(Count))
# Filter era_distribution_summarized to include only the top 5 buyer_names
era_distribution_top5 <- era_distribution_summarized %>%
  filter(buyer_name %in% buyer_name_total_count$buyer_name)

# Create horizontal stacked bar chart with a gradient from purple to pink
ggplot(era_distribution_top5, aes(x = Count/100000, y = reorder(buyer_name, Count), fill = Era)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 5 Pill Distributors Across Three Eras",
       x = "Count in 100,000",
       y = "Distributors") +
  theme_minimal() +
  scale_fill_viridis_d(name = "Era", option = "plasma", begin = 0.8, end = 0.2) +  # Gradient from purple to pink
  theme(axis.text.y = element_text(angle = 0, hjust = 1))
```


```{r}
head(era_distribution_top5)
```



```{r graph 3, message=FALSE, warning=FALSE}

# Filter data for the selected distributors
filtered_data <- df %>%
  filter(buyer_name %in% era_distribution_top5$buyer_name) %>%
  group_by(buyer_name) %>%
  summarise(average_dosage_unit = mean(dosage_unit, na.rm = TRUE)) %>%
  arrange(desc(average_dosage_unit))  # Arrange in descending order of average dosage unit

# Plot average dosage unit for the selected distributors
ggplot(filtered_data, aes(x = average_dosage_unit, y = reorder(buyer_name, average_dosage_unit) )) +
  geom_bar(stat = "identity", fill = "#6c04a4") +
  labs(title = "Average Dosage Unit for Selected Distributors",
       x ="Average Dosage Unit",
       y = "Distributor")+
  theme_minimal() 
```


```{r misleading graph 3, message=FALSE, warning=FALSE}
filtered_data <- df %>%
  filter(buyer_name %in% era_distribution_top5$buyer_name) %>%
  group_by(buyer_name) %>%
  summarise(average_dosage_unit = sum(dosage_unit, na.rm = TRUE)) %>%
  arrange(desc(average_dosage_unit)) 


ggplot(filtered_data, aes(x = average_dosage_unit/100000, y = reorder(buyer_name, average_dosage_unit) )) +
  geom_bar(stat = "identity", fill = "#6c04a4") +
  labs(title = "Dosage Unit for Selected Distributors",
       x ="Dosage Unit in 100,000",
       y = "Distributor") +
  theme_minimal() 
```